export const DirectionIds = {
  CRYPTO_TO_CASH: 1,
  CRYPTO_TO_CASHLESS: 2,
  CRYPTO_TO_QR: 3,
  CASH_TO_CRYPTO: 4,
  CASH_TRANSFER_WORLDWIDE: 5,
  INTERNATIONAL_PAYMENT: 6,
  CRYPTO_EXCHANGE_RISK: 7,
  LEGALIZATION: 8,
  OTHER: 9,
}
